### ISSUE TITLE
Problem with Win 7 install

### ISSUE THREAD

**Issue by ArthurSpirling** [quanteda/spacyr#124] opened 2018-07-06 14:29 UTC
I'm following these instructions: https://github.com/quanteda/spacyr/blob/master/inst/doc/WINDOWS.md

Some notes: 

- current version of Python is 3.6.6, not 3.6.1
- Instructions refer to "Virtual Studio", but surely you mean "Visual Studio"?
- obtaining Visual Studio 2015 requires a sign in: https://visualstudio.microsoft.com/vs/older-downloads/
Are you advising people create an acct in order to get the compiler?

Instead, I tried to install VS 2017.  But note that doing so means one has to pick various add-on/tools (e.g c++, python or not).  But there is no advice here about which to pick.

I had no problem downloading python 3.6.6.  I chose “Add Python.exe to Path”, but using the Admin Command Prompt, 
```
pip3 install spacy
```
ultimately returns

```
fatal error C1083 Cannot open include file: 'io.h': No such file...
```

Note I am using Windows 7.

**Comment by ArthurSpirling** [comment] 2018-07-06 14:40
more feedback. Instead, I tried to follow the instructions here: https://github.com/quanteda/spacyr, in the read me.

Notes:
-  "You can check it by entering conda --version in Console." which console?  Also, should anaconda be in the path?  That seems to not be recommended, but presumably it should be associated with python 3.6?
- following the other instructions, including `spacy_install()` starts with the following warning
```
Installing spaCy...
'chcp' is not recognized as an internal or external command,
operable program or batch file.
```
and then returns wheel build fails (for everything) and ultimately the following error message
```
Error: Error 1 occurred installing packages into conda environment spacy_condaenv
In addition: Warning message:
running command '"C:/PROGRA~3/MINICO~1/Scripts/activate" spacy_condaenv && pip install --upgrade --ignore-installed "spacy"' had status 1 
```

**Comment by kbenoit** [comment] 2018-07-06 16:38
I just tested this, and it worked for me on my Windows 7 VM. Here's what I did:

1. Updated R to 3.5.1.  
2. Installed **spacyr** from CRAN (0.9.9).
3. Installed Anaconda, following this output:
```r
> spacy_install()
Error: Conda installation failed (no conda binary found)

Install Anaconda 3.x for Windows (https://www.anaconda.com/download/#windows)
before installing spaCy
```
When installing Anaconda, I checked the item in the next to last dialog box, to make the Anaconda the default Python environment.
4. After the Anaconda installation completed, I reran:
```r
> spacy_install()
A new conda environment "spacy_condaenv" will be created and 
spaCy and language model(s): en will be installed.  Proceed? 

1: No
2: Yes

Selection: 2
Creating spacy_condaenv conda environment for spaCy installation...
Solving environment: ...working... done
...
```
and it installed everything it needed into a conda environment.

Note that this didn't work completely. Instead, it says:
```r
...
Installing collected packages: en-core-web-sm
  Running setup.py install for en-core-web-sm: started
    Running setup.py install for en-core-web-sm: finished with status 'done'
Successfully installed en-core-web-sm-2.0.0

    Error: Couldn't link model to 'en'
    Creating a symlink in spacy/data failed. Make sure you have the required
    permissions and try re-running the command as admin, or use a
    virtualenv. You can still import the model as a module and call its
    load() method, or create the symlink manually.

    C:\Users\kbenoit\ANACON~1\envs\spacy_condaenv\lib\site-packages\en_core_web_sm
    -->
    C:\Users\kbenoit\ANACON~1\envs\spacy_condaenv\lib\site-packages\spacy\data\en


    Creating a shortcut link for 'en' didn't work (maybe you don't have
    admin permissions?), but you can still load the model via its full
    package name: nlp = spacy.load('{name}')
    Download successful but linking failed

Language model "en" is successfully installed


Installation complete.
Condaenv: spacy_condaenv; Langage model(s): en
```
So then I repeated this step, after exiting R and re-launching it as Administrator. (Google "windows 7 run as administrator" for instructions as to how.) The linking was then successful.

Then I got this message.
```r
> library("spacyr")
> spacy_initialize()
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```

@amatsuo ??

**Comment by ArthurSpirling** [comment] 2018-07-06 17:29
ah, ok.  Happy to update R etc, but I'll await @amatsuo's judgement on the err msg.

**Comment by kbenoit** [comment] 2018-07-06 17:43
If you have Python running, apart from Anaconda, you should be able to point to it using
```r
spacy_initialize(python_executable = "c:\python36\bin\")
```
(replacing the argument value of course with your executable)

And seriously...Windows 7 ???

**Comment by kbenoit** [comment] 2018-07-06 17:44
Here's an alternative to the full monty Anaconda: https://conda.io/miniconda.html

**Comment by ArthurSpirling** [comment] 2018-07-06 18:04
It can't install spacy, for the reasons I mentioned above -- throws an error message about `C1083`. Obv, this is *prior* to any initialize call in R itself.

**Comment by amatsuo** [comment] 2018-07-07 09:18
It took a lot of trials, but I was able to install spacy on my Windows with a brand-new installation of VS2017. The point is to install C++ build environment on VS2017. I will post details later today.

**Comment by amatsuo** [comment] 2018-07-07 11:07
Here are the steps to make it work:

1. Install [Visual Studio Community 2017](https://visualstudio.microsoft.com/downloads/)
1. Launch Visual Studio Installer (Picture 1)
1. Install Desktop Development with C++ (Picture 2)

Before the spep 3, I got the same error as @ArthurSpirling got, but being C++ components installed, I was able to install spacy.

![picture 1](https://user-images.githubusercontent.com/8436792/42410217-df49e52a-81dd-11e8-82a7-384c7cf7077a.png)

![picture 2](https://user-images.githubusercontent.com/8436792/42410224-fa94851a-81dd-11e8-9b9d-4952a6b90052.png)

**Comment by ArthurSpirling** [comment] 2018-07-08 21:30
I'll give this a look shortly on my laptop (which runs Windows 10.

**Comment by ArthurSpirling** [comment] 2018-07-10 13:54
Trying this morning, and the install worked without a problem.  However:
Language model "en" is successfully installed


```
Installation complete.
Condaenv: spacy_condaenv; Langage model(s): en

> spacy_initialize()
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  AttributeError: module 'pip' has no attribute 'get_installed_distributions'

Detailed traceback: 
  File "<string>", line 5, in <module>
```

**Comment by amatsuo** [comment] 2018-07-10 13:58
This is due to our slow update on CRAN (c.f. #120, #114). The issue is fixed on the master github repo months ago. 

Please re-install with:
```r
devtools::install_github("quanteda/spacyr")
```

**Comment by ArthurSpirling** [comment] 2018-07-10 16:21
thanks, now working! I think it would be very helpful to explain the VS download and conda download as separate steps in the same markdown.

**Closed** 2018-11-15 10:55 UTC
