### ISSUE TITLE
Cannot initialize spacyr

### ISSUE THREAD

**Issue by annamay22** [quanteda/spacyr#110] opened 2018-05-07 14:48 UTC
Hi,

I get the following error when trying to initialize spacyr:

```
> library(spacyr)
> spacy_initialize(model = "en")
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  AttributeError: module 'pip' has no attribute 'get_installed_distributions'
```
I thought the issue might be connected to some changes in the pip internal API's as seen [here] (https://github.com/pypa/pip/issues/5154) and [here](https://github.com/Miserlou/Zappa/issues/1471), but the problem persist after downgrading to pip==9.0.1.

I would appreciate any help on resolving this issue.

Thanks in advance!

Session information:
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacyr_0.9.9   rJava_0.9-9    quanteda_1.2.0

**Comment by maybemkl** [comment] 2018-05-08 00:01
I have the same issue, what specific steps did you go through to solve it? Did you have conda and anaconda installed and what approach did you take to reinstalling them?

**Comment by kbenoit** [comment] 2018-05-08 07:06
With the newest version of spacyr, you should be able to install what you need using `spacy_install()`. Please try that.

**Comment by maybemkl** [comment] 2018-05-08 07:25
Thanks @kbenoit, I actually realised I had the wrong version of pip in the spacy venv. Downgrading that to pip 9.0.1 fixed the issue!

**Comment by dmklotz** [comment] 2018-05-15 14:51
Since I'm new to using Python within R, It wasn't immediately clear to me how to downgrade pip within a condaenv as @maybemkl suggested.  In case anybody else runs into the same issue, I thought I'd spell out the details:

`reticulate::conda_install(envname = "spacy_condaenv", packages = 'pip==9.0.1')`

**Comment by amatsuo** [comment] 2018-05-15 16:04
Interesting. 
@maybemkl 
do you have the error message you got with the newer version of pip?

@kbenoit 
in any case, we may have to specify pip version for installing a conda environment.

**Comment by amatsuo** [comment] 2018-05-18 11:51
It turned out this is the cause of travis-ci failure. I will keep this issue open until the build succeeds.

**Comment by amatsuo** [comment] 2018-05-22 11:41
This issue should be resolved in the current master

**Comment by amatsuo** [comment] 2018-05-22 11:41
This issue should be resolved in the current master

**Closed by amatsuo** 2018-05-22 11:41 UTC
